[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00e5ff"
backgroundColor = "#070b1a"
secondaryBackgroundColor = "#101c44"
textColor = "#f6fbff"
font = "sans serif"
